"""init

Revision ID: 6d6df33869c2
Revises: 
Create Date: 2026-04-16 17:49:53.498463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6df33869c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Aml_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Authorization_Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.CheckConstraint('id >= 100000000 AND id <= 999999999'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Card_Category',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Card_Status',
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clients',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_male', sa.Boolean(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Contact_Type',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credit_Plans',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('min_term_months', sa.Integer(), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=True),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.Column('late_payment_fee', sa.Integer(), nullable=True),
    sa.Column('requires_collateral', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('requires_income_proof', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('requires_credit_history', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credit_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Currency',
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deposit_Plan',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('count_month', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimal_amount', sa.Integer(), nullable=True),
    sa.Column('early_withdrawal_rate', sa.DECIMAL(), nullable=True),
    sa.Column('early_withdrawal_fee', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deposit_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Directions',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Document_Type',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employment_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Kyc_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Mcc_Codes',
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('id >= 1000 AND id <= 9999'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Payment_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transaction_Status',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transaction_Types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Accounts',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['Currency.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Account_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client_Addresses',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_resident', sa.Boolean(), server_default=sa.text('(true)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('Client_Contacts',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact_type_id', sa.Integer(), nullable=False),
    sa.Column('contact_value', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_type_id'], ['Contact_Type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client_Documents',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_value', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['Document_Type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client_Employment',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['Currency.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Employment_Status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('Client_Verifications',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('kyc_status_id', sa.Integer(), nullable=False),
    sa.Column('aml_status_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.ForeignKeyConstraint(['aml_status_id'], ['Aml_Status.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kyc_status_id'], ['Kyc_Status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('Transactions',
    sa.Column('transaction_uuid', sa.String(length=36), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('mcc_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('amount != 0'),
    sa.ForeignKeyConstraint(['currency_id'], ['Currency.id'], ),
    sa.ForeignKeyConstraint(['mcc_id'], ['Mcc_Codes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Transaction_Status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['Transaction_Types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Account_Balances',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cards',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_category_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('card_number_hash', sa.String(length=256), nullable=False),
    sa.Column('card_number_last4', sa.String(length=4), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('expiration_month', sa.Integer(), nullable=False),
    sa.Column('expiration_year', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cvv_hash', sa.String(length=256), nullable=True),
    sa.Column('activated_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('pin_attempts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint('expiration_month BETWEEN 1 AND 12'),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['card_category_id'], ['Card_Category.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Card_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credits',
    sa.Column('credit_number', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('loan_account_id', sa.Integer(), nullable=False),
    sa.Column('repayment_account_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('end_date > issued_date'),
    sa.CheckConstraint('payment_due_day BETWEEN 1 AND 31'),
    sa.CheckConstraint('principal_amount > 0'),
    sa.CheckConstraint('remaining_amount >= 0'),
    sa.ForeignKeyConstraint(['currency_id'], ['Currency.id'], ),
    sa.ForeignKeyConstraint(['loan_account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['Credit_Plans.id'], ),
    sa.ForeignKeyConstraint(['repayment_account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Credit_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deposits',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partial_withdrawal_allowed', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['Deposit_Plan.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Deposit_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Interbank_Settlements',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['Banks.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['Directions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ledger_Entries',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('credit', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('credit >= 0'),
    sa.CheckConstraint('debit + credit > 0'),
    sa.CheckConstraint('debit >= 0'),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transaction_Parties',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('external_account_number', sa.String(length=32), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['Banks.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['Directions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Card_Authorizations',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Cards.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Authorization_Status.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credit_Payment_Schedules',
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Integer(), nullable=False),
    sa.Column('interest_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.CheckConstraint('interest_amount >= 0'),
    sa.CheckConstraint('payment_number > 0'),
    sa.CheckConstraint('principal_amount >= 0'),
    sa.CheckConstraint('total_amount = principal_amount + interest_amount'),
    sa.ForeignKeyConstraint(['credit_id'], ['Credits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['Payment_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clearing_Transactions',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('external_bank', sa.String(length=20), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['authorization_id'], ['Card_Authorizations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credit_Payments',
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('principal_paid', sa.Integer(), nullable=False),
    sa.Column('interest_paid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('late_fee_paid', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('amount = principal_paid + interest_paid + late_fee_paid'),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['credit_id'], ['Credits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['Credit_Payment_Schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Credit_Payments')
    op.drop_table('Clearing_Transactions')
    op.drop_table('Credit_Payment_Schedules')
    op.drop_table('Card_Authorizations')
    op.drop_table('Transaction_Parties')
    op.drop_table('Ledger_Entries')
    op.drop_table('Interbank_Settlements')
    op.drop_table('Deposits')
    op.drop_table('Credits')
    op.drop_table('Cards')
    op.drop_table('Account_Balances')
    op.drop_table('Transactions')
    op.drop_table('Client_Verifications')
    op.drop_table('Client_Employment')
    op.drop_table('Client_Documents')
    op.drop_table('Client_Contacts')
    op.drop_table('Client_Addresses')
    op.drop_table('Accounts')
    op.drop_table('Transaction_Types')
    op.drop_table('Transaction_Status')
    op.drop_table('Payment_Status')
    op.drop_table('Mcc_Codes')
    op.drop_table('Kyc_Status')
    op.drop_table('Employment_Status')
    op.drop_table('Document_Type')
    op.drop_table('Directions')
    op.drop_table('Deposit_Status')
    op.drop_table('Deposit_Plan')
    op.drop_table('Currency')
    op.drop_table('Credit_Status')
    op.drop_table('Credit_Plans')
    op.drop_table('Contact_Type')
    op.drop_table('Clients')
    op.drop_table('Card_Status')
    op.drop_table('Card_Category')
    op.drop_table('Banks')
    op.drop_table('Authorization_Status')
    op.drop_table('Aml_Status')
    op.drop_table('Account_Status')
    # ### end Alembic commands ###
